apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: "goserver"
          image: ederfmatos/full-cycle-go-kubernetes:v11

          resources:
            requests:
              cpu: "0.1"
              memory: 25Mi
            limits:
              cpu: "0.15"
              memory: 30Mi

          startupProbe:
            httpGet:
              path: "/health"
              port: 8080
            periodSeconds: 3
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: "/health"
              port: 8080
            periodSeconds: 3
            failureThreshold: 1

          livenessProbe:
            httpGet:
              path: "/health"
              port: 8080
            periodSeconds: 2
            timeoutSeconds: 2
            failureThreshold: 1
            successThreshold: 1

          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret
